"""add payment_method and status to order

Revision ID: 4abcb41f47fc
Revises: 29f7e3842766
Create Date: 2025-10-01 11:12:04.356352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4abcb41f47fc'
down_revision = '29f7e3842766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('customer_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('customer_phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('total',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('items')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
        batch_op.add_column(sa.Column('items', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.alter_column('total',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('customer_phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               existing_nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
