"""Allow null order_id in feedback

Revision ID: 68d2a89e8b6f
Revises: a56ca5639baa
Create Date: 2025-10-05 01:36:38.584548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68d2a89e8b6f'
down_revision = 'a56ca5639baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
