"""Update order schema with varchar status & payment, add price & notes to order_items

Revision ID: 8a0fc695433d
Revises: fdb754147248
Create Date: 2025-10-01 16:13:50.124591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0fc695433d'
down_revision = 'fdb754147248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('status')
        batch_op.drop_column('price')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
