"""add amount_paid and change_due to order

Revision ID: fdb754147248
Revises: 4abcb41f47fc
Create Date: 2025-10-01 12:55:34.874015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb754147248'
down_revision = '4abcb41f47fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('change_due', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('change_due')
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
